Repository ONE-TEAM-ONE/OneEat, pull requests merged in 2024-11, with the labels that each got.

#8 feat : 주문 목록 조회 #7
  src/main/java/com/sparta/oneeat/order/Service/OrderService.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
  src/main/java/com/sparta/oneeat/order/controller/OrderController.java
  src/main/java/com/sparta/oneeat/order/dto/OrderListDto.java
  src/main/java/com/sparta/oneeat/order/entity/Order.java
  src/main/java/com/sparta/oneeat/order/entity/OrderStatusEnum.java
  src/main/java/com/sparta/oneeat/order/entity/OrderTypeEnum.java
  src/main/java/com/sparta/oneeat/order/repository/OrderRepository.java
  src/main/java/com/sparta/oneeat/store/repository/StoreRepository.java
  src/main/java/com/sparta/oneeat/user/repository/UserRepository.java
Labels: 기능

#9 feat : 주문 상세 조회 #7
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/order/Service/OrderService.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
  src/main/java/com/sparta/oneeat/order/controller/OrderController.java
  src/main/java/com/sparta/oneeat/order/dto/OrderDetailDto.java
  src/main/java/com/sparta/oneeat/order/dto/OrderMenuDto.java
Labels: 기능

#10 Feature/modify status
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/order/Service/OrderService.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
  src/main/java/com/sparta/oneeat/order/controller/OrderController.java
  src/main/java/com/sparta/oneeat/order/entity/Order.java
Labels: 기능

#16 feat : ai 요청 및 메뉴 생성 구현
  build.gradle
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/dto/request/AiCallRequestDto.java
  src/main/java/com/sparta/oneeat/menu/dto/request/AiRequestDto.java
  src/main/java/com/sparta/oneeat/menu/dto/request/MenuRequestDto.java
  src/main/java/com/sparta/oneeat/menu/dto/response/AiResponseDto.java
  src/main/java/com/sparta/oneeat/menu/dto/response/MenuResponseDto.java
  src/main/java/com/sparta/oneeat/menu/entity/Ai.java
  src/main/java/com/sparta/oneeat/menu/entity/Menu.java
  src/main/java/com/sparta/oneeat/menu/entity/MenuStatusEnum.java
  src/main/java/com/sparta/oneeat/menu/repository/AiRepository.java
  src/main/java/com/sparta/oneeat/menu/repository/MenuRepository.java
  src/main/java/com/sparta/oneeat/menu/service/AiService.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
  src/main/java/com/sparta/oneeat/order/entity/OrderTypeEnum.java
  src/main/java/com/sparta/oneeat/order/entity/PaymentStatusEnum.java
  src/main/java/com/sparta/oneeat/store/entity/Category.java
  src/main/java/com/sparta/oneeat/store/entity/StoreCategoryEnum.java
  src/main/java/com/sparta/oneeat/store/entity/StoreStatusEnum.java
  src/main/java/com/sparta/oneeat/store/repository/StoreRepository.java
  src/main/java/com/sparta/oneeat/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/sparta/oneeat/common/env/EnvTest.java
Labels: 기능

#14 feat : Auth 도메인 API 구현 #13
  build.gradle
  src/main/java/com/sparta/oneeat/auth/controller/AuthController.java
  src/main/java/com/sparta/oneeat/auth/dto/LoginRequestDto.java
  src/main/java/com/sparta/oneeat/auth/dto/LoginResponseDto.java
  src/main/java/com/sparta/oneeat/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/oneeat/auth/dto/SignupResponseDto.java
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/oneeat/auth/service/AuthService.java
  src/main/java/com/sparta/oneeat/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/oneeat/auth/service/UserDetailsImpl.java
  src/main/java/com/sparta/oneeat/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/sparta/oneeat/common/config/PasswordConfig.java
  src/main/java/com/sparta/oneeat/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/common/util/JwtUtil.java
  src/main/java/com/sparta/oneeat/store/entity/DeliveryRegion.java
  src/main/java/com/sparta/oneeat/user/entity/User.java
  src/main/java/com/sparta/oneeat/user/entity/UserAddress.java
  src/main/java/com/sparta/oneeat/user/entity/UserRoleEnum.java
  src/main/java/com/sparta/oneeat/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/sparta/oneeat/common/env/EnvTest.java
Labels: 기능

#25 fix : 로그인 DTO 바인딩 오류 수정 #24
  src/main/java/com/sparta/oneeat/auth/dto/LoginRequestDto.java
Labels: 버그

#27 Feature/read menu
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/repository/MenuRepository.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
  src/main/java/com/sparta/oneeat/store/entity/StoreCategoryEnum.java
  src/main/java/com/sparta/oneeat/store/entity/StoreStatusEnum.java
Labels: 기능

#30 feat : 주문 생성 #7
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/order/Service/OrderService.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
  src/main/java/com/sparta/oneeat/order/controller/OrderController.java
  src/main/java/com/sparta/oneeat/order/dto/CreateOrderReqDto.java
  src/main/java/com/sparta/oneeat/order/dto/CreateOrderResDto.java
  src/main/java/com/sparta/oneeat/order/entity/Order.java
  src/main/java/com/sparta/oneeat/order/entity/OrderMenu.java
  src/main/java/com/sparta/oneeat/order/repository/OrderMenuRepository.java
Labels: 기능

#32 fix : JWT 토큰 처리 중 발생하는 에러 수정 #31
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/oneeat/common/config/WebSecurityConfig.java
  src/main/java/com/sparta/oneeat/common/util/JwtUtil.java
Labels: 버그

#33 feat : 메뉴 수정 #2
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/entity/Menu.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 기능

#38 fix : Swagger 접근 문제 관련 JWT 필터 로직 수정 #37
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthorizationFilter.java
Labels: 버그

#42 fix : 회원 API 로직 문제 수정
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/user/service/UserServiceImpl.java
Labels: 버그

#47 Feature/create store category
  src/main/java/com/sparta/oneeat/category/controller/StoreCategoryController.java
  src/main/java/com/sparta/oneeat/category/dto/CreateCategoryReqDto.java
  src/main/java/com/sparta/oneeat/category/dto/CreateCategoryResDto.java
  src/main/java/com/sparta/oneeat/category/entity/Category.java
  src/main/java/com/sparta/oneeat/category/repository/StoreCategotyRepository.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryService.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/menu/service/AiService.java
  src/main/java/com/sparta/oneeat/store/entity/Store.java
  src/main/java/com/sparta/oneeat/store/entity/StoreCategoryEnum.java
Labels: 기능

#45 refacter : 하드코딩된 userId 부분을 UserDetailsImpl로 수정 #43
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/service/AiService.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 리팩토링

#44 Refactoring/authentication
  src/main/java/com/sparta/oneeat/order/Service/OrderService.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
  src/main/java/com/sparta/oneeat/order/controller/OrderController.java
  src/main/java/com/sparta/oneeat/payment/controller/PaymentController.java
  src/main/java/com/sparta/oneeat/review/controller/ReviewController.java
Labels: 리팩토링

#40 Feature : 메뉴 숨김, 삭제 구현
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/repository/MenuRepository.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 기능

#48 Feature/ 카테고리 수정
  src/main/java/com/sparta/oneeat/category/controller/StoreCategoryController.java
  src/main/java/com/sparta/oneeat/category/dto/UpdateCategoryReqDto.java
  src/main/java/com/sparta/oneeat/category/entity/Category.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryService.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
Labels: 기능

#50 Feature/ 카테고리 삭제 처리
  src/main/java/com/sparta/oneeat/category/controller/StoreCategoryController.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryService.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
  src/main/java/com/sparta/oneeat/store/repository/StoreRepository.java
Labels: 기능

#51 Feature/ 카테고리 수정 처리
  src/main/java/com/sparta/oneeat/category/controller/StoreCategoryController.java
  src/main/java/com/sparta/oneeat/category/entity/Category.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryService.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
Labels: 기능

#55 feat : 카테고리 목록 조회 #46
  src/main/java/com/sparta/oneeat/category/controller/StoreCategoryController.java
  src/main/java/com/sparta/oneeat/category/dto/CategoryListResDto.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryService.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
Labels: 기능

#49 feature : 회원 주소 도메인 API 구현 #35
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/user/controller/UserAddressController.java
  src/main/java/com/sparta/oneeat/user/dto/AddressModifyRequestDto.java
  src/main/java/com/sparta/oneeat/user/dto/AddressRequestDto.java
  src/main/java/com/sparta/oneeat/user/dto/AddressResponseDto.java
  src/main/java/com/sparta/oneeat/user/entity/User.java
  src/main/java/com/sparta/oneeat/user/entity/UserAddress.java
  src/main/java/com/sparta/oneeat/user/repository/UserAddressRepository.java
  src/main/java/com/sparta/oneeat/user/service/UserAddressService.java
  src/main/java/com/sparta/oneeat/user/service/UserAddressServiceImpl.java
Labels: 기능

#53 fix : Auditing null 입력 문제 해결 #52
  src/main/java/com/sparta/oneeat/common/config/AuditorAwareConfig.java
Labels: 버그

#58 Refactor/auth
  src/main/java/com/sparta/oneeat/auth/controller/AuthController.java
  src/main/java/com/sparta/oneeat/auth/dto/SignupRequestDto.java
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/sparta/oneeat/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/sparta/oneeat/auth/service/AuthService.java
  src/main/java/com/sparta/oneeat/auth/service/AuthServiceImpl.java
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/user/entity/User.java
Labels: 리팩토링

#63 Refactor/useraddress
  src/main/java/com/sparta/oneeat/user/controller/UserAddressController.java
  src/main/java/com/sparta/oneeat/user/dto/AddressModifyRequestDto.java
  src/main/java/com/sparta/oneeat/user/dto/AddressRequestDto.java
  src/main/java/com/sparta/oneeat/user/entity/UserAddress.java
  src/main/java/com/sparta/oneeat/user/service/UserAddressService.java
  src/main/java/com/sparta/oneeat/user/service/UserAddressServiceImpl.java
Labels: 리팩토링

#69 refacter : 메뉴 조회 시 숨김 처리 제외
  src/main/java/com/sparta/oneeat/menu/repository/MenuRepository.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 리팩토링

#71 refacter : 중복 코드 분리
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/repository/MenuRepository.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 리팩토링

#73 refactor : 유저, 주소 도메인 숨김 제외 처리
  src/main/java/com/sparta/oneeat/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/sparta/oneeat/user/repository/UserAddressRepository.java
  src/main/java/com/sparta/oneeat/user/repository/UserRepository.java
  src/main/java/com/sparta/oneeat/user/service/UserAddressServiceImpl.java
Labels: 리팩토링

#76 chore : Hibernate SQL Dialect 설정 #75
  src/main/java/com/sparta/oneeat/common/util/JwtUtil.java
  src/main/resources/application.yml
Labels: 설정

#84 fix : 주문생성 시 해당 가게의 메뉴가 아니더라도 생성되는 에러 처리 #82
  src/main/java/com/sparta/oneeat/common/exception/ExceptionType.java
  src/main/java/com/sparta/oneeat/order/Service/OrderServiceImpl.java
Labels: 버그

#85 refacter : 인가 설정 최신화 #81
  src/main/java/com/sparta/oneeat/common/config/WebSecurityConfig.java
Labels: 리팩토링

#88 fix : 결제 상태 변경 시 주문 상태가 올바르게 변경되지 않는 문제 수정 #83
  src/main/java/com/sparta/oneeat/payment/service/PaymentServiceImpl.java
Labels: 버그

#93 fix : 숨김 설정된 가게 카테고리가 조회 결과에 포함되는 문제 수정 #92
  src/main/java/com/sparta/oneeat/category/repository/StoreCategotyRepository.java
  src/main/java/com/sparta/oneeat/category/service/StoreCategoryServiceImpl.java
Labels: 버그

#94 fix : 패스워드 관련 잘못된 로직 수정
  src/main/java/com/sparta/oneeat/user/controller/UserController.java
  src/main/java/com/sparta/oneeat/user/dto/AddressModifyRequestDto.java
  src/main/java/com/sparta/oneeat/user/service/UserService.java
  src/main/java/com/sparta/oneeat/user/service/UserServiceImpl.java
Labels: 버그

#89 fix : 회원가입시 입력한 주소를 주소록에 추가하도록 수정 #87
  src/main/java/com/sparta/oneeat/auth/service/AuthServiceImpl.java
Labels: 버그

#97 Fix/ 메뉴 조회 매핑 메서드 수정
  src/main/java/com/sparta/oneeat/menu/controller/MenuController.java
  src/main/java/com/sparta/oneeat/menu/service/MenuService.java
Labels: 버그
